language: node_js

node_js:
  - node
  - lts/*

cache:
  npm: false
  directories:
    - $HOME/.npm

before_script:
- npm install

script:
- npm run lint
- npm test

after_script:
- npm run ci.coverage
